name: Python application

on: [push]

env:
  ml-ws-connection: azmldemows
  ml-ws: aml-demo
  ml-rg: aml-demo
  ml-ct: cpu-cluster-1
  ml-path: models/diabetes
  ml-exp: exp-test 
  ml-model-name: diabetes-model # Model name
  ml-aks-name: aks-prod # AKS cluster name
  ml-model-path: outputs/ridge_0.90.pkl 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@master
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: install azmlcli
      run: az extension add -n azure-cli-ml
    - name: attach to workspace
      working-directory: ${{env.ml-path}}
      run: az ml folder attach -w myworkspace -g myresourcegroup
    - name: create remote compute
      working-directory: ${{env.ml-path}}
      run: az ml computetarget create amlcompute -n ${{env.ml-ct}} --vm-size STANDARD_D2_V2 --max-nodes 4
    - name: train model
      working-directory: ${{env.ml-path}}
      run: az ml run submit-script -c config/train --ct ${{env.ml-ct}} -e ${{env.ml-exp}} -t run.json
    - name: register model
      working-directory: ${{env.ml-path}}
      run: az ml model register -n ${{env.ml-model-name}} -f run.json --asset-path ${{env.ml-model-path}} -t model.json
    - name: deploy model to ACI
      working-directory: ${{env.ml-path}}
      run: az ml model deploy -n acicicd3 -f model.json --ic config/inference-config.yml --dc config/deployment-config-aci.yml --overwrite
